# Generated by Django 5.2.6 on 2026-08-17 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='New Season Arrivals', max_length=100)),
                ('heading', models.CharField(default='Style that Speaks. Fashion that Lasts.', max_length=200)),
                ('subheading', models.TextField(default='Discover the perfect blend of traditional elegance and modern style at EBASI STORE. Your destination for authentic Assamese Mekhela Sadors, sarees, and handcrafted fashion.')),
                ('cta_text', models.CharField(default='Shop Collection', max_length=100)),
                ('cta_link', models.CharField(default='/shop', max_length=255)),
                ('secondary_cta_text', models.CharField(default='Follow Us', max_length=100)),
                ('secondary_cta_link', models.CharField(default='https://www.instagram.com/ebasistore_traditionalattire/', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/hero/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif'])])),
                ('image_url_fallback', models.URLField(blank=True, default='https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=1200&auto=format&fit=crop', max_length=500)),
                ('image_alt', models.CharField(default='Authentic handcrafted Assamese Mekhela Sador and traditional boutique collection', max_length=255)),
                ('floating_card_title', models.CharField(default='Handcrafted Mekhela Sador', max_length=200)),
                ('floating_card_subtitle', models.CharField(default='Explore our handpicked curation of elegant Assamese wear.', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Hero Section',
                'verbose_name_plural': 'Homepage Hero Section',
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('purpose', models.CharField(choices=[('logo', 'Store Logo'), ('favicon', 'Favicon'), ('og_image', 'Social Share Image'), ('hero', 'Hero Banner'), ('about', 'About Page Media'), ('general', 'General Media')], default='general', max_length=50)),
                ('file', models.ImageField(upload_to='cms/media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg', 'ico', 'avif'])])),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Asset',
                'verbose_name_plural': 'Media Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('about', 'About Us Page'), ('privacy-policy', 'Privacy Policy'), ('terms-of-service', 'Terms of Service'), ('contact', 'Contact Page')], max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('intro', models.TextField(blank=True)),
                ('content_json', models.JSONField(blank=True, default=dict, help_text='Structured sections, articles, or values.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='cms/pages/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif'])])),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='cms/pages/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif'])])),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('last_updated_date', models.CharField(blank=True, default='January 15, 2024', max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Contents',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], max_length=50, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('handle', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('is_enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ms Ebasi Store', max_length=200)),
                ('brand_name', models.CharField(default='EBASI STORE', max_length=200)),
                ('enterprise_name', models.CharField(default='EBASI ENTERPRISE', max_length=200)),
                ('business_type', models.CharField(default='Boutique / Clothing brand', max_length=200)),
                ('tagline', models.CharField(default='Style that Speaks. Fashion that Lasts.', max_length=300)),
                ('short_description', models.TextField(blank=True, default='Authentic Assamese traditional attire boutique. Specializing in handcrafted Deori Egu-Jokasiba, Mekhela Sador, Gamusa, and traditional silk weaves with direct WhatsApp customer assistance.')),
                ('long_description', models.TextField(blank=True, default='Celebrating the timeless artistry of Assamese handlooms, Deori Egu-Jokasiba, and authentic ethnic wear directly from local weavers to your wardrobe.')),
                ('phone', models.CharField(default='073992 91242', max_length=50)),
                ('phone_raw', models.CharField(default='917399291242', max_length=50)),
                ('phone_display', models.CharField(default='+91 73992 91242', max_length=50)),
                ('whatsapp_number', models.CharField(default='917399291242', max_length=50)),
                ('email', models.EmailField(blank=True, default='contact@ebasistore.com', max_length=254)),
                ('address_street', models.CharField(default='Railway, Station Rd, opposite Parmananda Academy', max_length=255)),
                ('address_locality', models.CharField(default='Nagakhelia No.2', max_length=200)),
                ('address_city', models.CharField(default='Dhemaji', max_length=100)),
                ('address_state', models.CharField(default='Assam', max_length=100)),
                ('address_postal_code', models.CharField(default='787057', max_length=20)),
                ('address_country', models.CharField(default='India', max_length=100)),
                ('address_full', models.TextField(default='Railway, Station Rd, opposite Parmananda Academy, Nagakhelia No.2, Dhemaji, Assam 787057, India')),
                ('plus_code', models.CharField(default='FHG4+PH, Dhemaji, Assam', max_length=100)),
                ('google_maps_embed_url', models.TextField(blank=True, default='https://maps.google.com/maps?q=Railway,+Station+Rd,+opposite+Parmananda+Academy,+Nagakhelia+No.2,+Dhemaji,+Assam+787057&t=&z=15&ie=UTF8&iwloc=&output=embed')),
                ('google_maps_directions_url', models.TextField(blank=True, default='https://www.google.com/maps/dir/?api=1&destination=Railway,+Station+Rd,+opposite+Parmananda+Academy,+Nagakhelia+No.2,+Dhemaji,+Assam+787057')),
                ('specialties', models.JSONField(blank=True, default=list, help_text='List of store specialties (e.g. Deori Egu-Jokasiba, Mekhela Sador, Gamusa).')),
                ('policies', models.JSONField(blank=True, default=dict, help_text='Store policies (e.g. payment terms, dispatch origin).')),
                ('meta_title', models.CharField(default='Ms Ebasi Store | Authentic Assamese Traditional Attire & Handlooms', max_length=200)),
                ('meta_description', models.TextField(default='Discover authentic Assamese Mekhela Sador, Deori Egu-Jokasiba, Gamusa, and traditional handloom silk attire at Ms Ebasi Store, Dhemaji, Assam.')),
                ('meta_keywords', models.CharField(blank=True, default='Assamese handloom, Mekhela Sador, Deori Egu-Jokasiba, Dhemaji boutique, Muga silk, Paat silk, Gamusa', max_length=500)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='cms/brand/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg', 'avif'])])),
                ('favicon_image', models.ImageField(blank=True, null=True, upload_to='cms/brand/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'ico', 'svg'])])),
                ('og_share_image', models.ImageField(blank=True, null=True, upload_to='cms/brand/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Profile',
                'verbose_name_plural': 'Store Profile',
            },
        ),
    ]
