# Generated by Django 5.2.6 on 2026-05-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHOP', '0003_alter_review_user_name_productvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, choices=[('trending', 'Trending'), ('new_arrival', 'New Arrival'), ('best_seller', 'Best Seller'), ('hot', 'Hot'), ('limited_edition', 'Limited Edition'), ('featured', 'Featured')], default=None, help_text='Select a promotional badge to display on the website.', max_length=50, null=True),
        ),
    ]
