# Generated by Django 5.2.6 on 2026-08-16 18:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHOP', '0004_product_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif'])]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif'])]),
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('search', 'Search Query'), ('wishlist_add', 'Wishlist Addition'), ('whatsapp_click', 'WhatsApp Conversion Click'), ('contact_submit', 'Contact Inquiry Submitted')], db_index=True, max_length=50)),
                ('product_name', models.CharField(blank=True, default='', help_text='Snapshot of the product name at the time of the event.', max_length=255)),
                ('path', models.CharField(blank=True, default='', help_text='URL path or full page where the event originated.', max_length=500)),
                ('search_query', models.CharField(blank=True, default='', help_text='Search term submitted by the customer.', max_length=255)),
                ('source', models.CharField(blank=True, default='', help_text='Specific CTA source or UI component (e.g. navbar, product_detail, sticky_bar, wishlist).', max_length=100)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', help_text='Anonymous visitor session identifier (privacy-safe, no personal data).', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional non-PII contextual details (e.g., selected size, quantity, filter categories).')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(blank=True, help_text='Associated product if this is a product-level event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='SHOP.product')),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='SHOP_analyt_event_t_c5f600_idx'), models.Index(fields=['product', '-created_at'], name='SHOP_analyt_product_1e199b_idx'), models.Index(fields=['session_id', '-created_at'], name='SHOP_analyt_session_2e240b_idx')],
            },
        ),
    ]
